### ISSUE TITLE
Pineko doesn't respect `_template.yaml`

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/pineko#105]
I've noticed pineko doesn't respect all options in `_template.yaml`. I've noticed with ` n_integration_cores` which gets filled as 0 regardless of what I put in the template.

This is with a fresh installation of `pineline[full]`.

I've noticed this one because my computer crashed after `eko` took every possible resource, but it might be other options that are not respected. I'll have a look whether there's something else (relevant for physics) being ignored or whether it is a problem of the `pineline` package in pypi.

**Comment by felixhekhorn** [comment]
just to exclude a trivial bug: are you editing the correct file? Recall that after https://github.com/NNPDF/pineko/pull/67 the `_template.yaml` is theory dependent ... I didn't run myself, but looking here https://github.com/NNPDF/pineko/blob/31b04262539dc71bf110b9f1ce09de6dde788cc7/src/pineko/evolve.py#L114 this looks reasonable

**Comment by scarlehoff** [comment]
Could be, I have a mess of theories and symbolic links. I `sed'ed` everything and worked. I'll have a proper look and either close or fix this.

**Comment by scarlehoff** [comment]
Yes, it was that. Thanks. I've also put a more reasonable value in the two theories that are there.
