### ISSUE TITLE
Write the git tag of the programs when version is not available

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/pineko#108]
Just as we do with nnpdf (I can port the code from n3fit to here) so that one can use a development version of eko or pineko and still get that information.

In light of https://github.com/NNPDF/theories_slim/issues/7#issuecomment-1642293486 this might be useful

(and, fair enough, it would be better to create all fktables with tagged versions of the code but everyone knows that's not what is going to happen in reality)

**Comment by AleCandido** [comment]
In principle, if you use a commit (or even a dirty version), poetry-dynamic-versioning should make the version with the full Git information (as it is happening in PineAPPL, using something like `git describe --always --dirty`).

**Comment by scarlehoff** [comment]
> poetry-dynamic-versioning should make the version ...

It was not being used (it's a dependency of pineko already but not used)

**Comment by AleCandido** [comment]
It was used, here:

https://github.com/NNPDF/pineko/blob/8207111d181cca7f70c86593810273718e2fb5f8/pyproject.toml#L76-L83

It was acting through a hook in Poetry (made available by the Poetry plugin system).

**Comment by AleCandido** [comment]
But the back-end (if properly working) might be even better, since whenever you attempt installation it will pull `poetry-dynamic-versioning` as build dependency, so it will `pip` to make sure that is always there.

**Comment by scarlehoff** [comment]
Yes, without the backend importlib would not see the right version.

**Comment by AleCandido** [comment]
> Yes, without the backend importlib would not see the right version.

I'm not sure if you really need the backend, or maybe just the dependency in `requires` (and then the hook would do the rest).
However, I assume that if the backend exists there will be a reason.
