### ISSUE TITLE
Generated renormalization SV does not work at N3LO (and beyond)

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/pineko#144]
[`ren_sv_coeffs`](https://github.com/NNPDF/pineko/blob/e2cb2415ff4c1a952956a5386dbee129b66217b5/src/pineko/scale_variations.py#L33) does not work at N3LO, as it seems hardcoded to NNLO:
https://github.com/NNPDF/pineko/blob/e2cb2415ff4c1a952956a5386dbee129b66217b5/src/pineko/scale_variations.py#L56-L63
If you don't want to do the fully general math (which I guess should be [Bell polynomials](https://en.wikipedia.org/wiki/Bell_polynomials) - look at the second formula image under properties), you could still do an explicit spell out (as N4LO is far future, hopefully) ...

The relevant coeffs can be found in the MHOU paper:
![grafik](https://github.com/NNPDF/pineko/assets/6421325/5e6d33ce-bada-42f7-b453-ed74fd84207a)

cc @giacomomagni

**Comment by andreab1997** [comment]
Yes for the moment N3LO ren sv is not supported but surely we can add (and I will as soon as I have time to do it). Is this needed now?

**Comment by giacomomagni** [comment]
Oh damn, thanks for checking @felixhekhorn, 
I completely overlooked at this. 

> Yes for the moment N3LO ren sv is not supported but surely we can add (and I will as soon as I have time to do it). Is this needed now?

Yes they are needed for DIS where we do have N3LO effects.

**Comment by giacomomagni** [comment]
But wait, for DIS we have them from Yadism, so is the code doing the correct thing here?

**Comment by andreab1997** [comment]
> Oh damn, thanks for checking @felixhekhorn, I completely overlooked at this as I never check it.
> 
> > Yes for the moment N3LO ren sv is not supported but surely we can add (and I will as soon as I have time to do it). Is this needed now?
> 
> Yes they are needed for DIS where we do have N3LO effects.

This I know but I believed that for DIS `yadism` would provide the scale variations

**Comment by felixhekhorn** [comment]
> This I know but I believed that for DIS `yadism` would provide the scale variations

yes, `yadism` can indeed provide all SV (both ren and fact) at all orders (you have to request it though)

I was more worried about n3loxs or Higgs (or in general the N3LO pheno)

**Comment by andreab1997** [comment]
> > This I know but I believed that for DIS `yadism` would provide the scale variations
> 
> yes, `yadism` can indeed provide all SV (both ren and fact) at all orders (you have to request it though)
> 
> I was more worried about n3loxs or Higgs (or in general the N3LO pheno)

For the moment we do not have even the N3LO central for most of the datasets, so we are not using anywhere the N3LO sv (apart from DIS and for few DY points, as far as I know)

**Comment by giacomomagni** [comment]
> yes, `yadism` can indeed provide all SV (both ren and fact) at all orders (you have to request it though)

wait at N3LO on ren scale are available in yadism:  https://github.com/NNPDF/yadism/issues/150

> I was more worried about n3loxs or Higgs (or in general the N3LO pheno)

So far I was using the scale varied KF or computing sv directly using the given n3lo code, but I believe this feature can be quite useful in pineko in future. 
And it doesn't require much work.

**Comment by felixhekhorn** [comment]
> > yes, `yadism` can indeed provide all SV (both ren and fact) at all orders (you have to request it though)
> 
> wait at N3LO on ren scale are available in yadism: [NNPDF/yadism#150](https://github.com/NNPDF/yadism/issues/150)

you're right and I'm wrong - there is neither fact. nor ren. SV at N3LO in yadism :scream: the ren should be here, but it isn't:
https://github.com/NNPDF/yadism/blob/3a2552c8e3c53f7d80c1d5d5b159c00df9240b8f/src/yadism/esf/scale_variations.py#L129

> 
> > I was more worried about n3loxs or Higgs (or in general the N3LO pheno)
> 
> So far I was using the scale varied KF or computing sv directly using the given n3lo code, but I believe this feature can be quite useful in pineko in future. And it doesn't require much work.

does this mean we the N3LO fits are safe for the moment? (or do we need to panic?)

**Comment by andreab1997** [comment]
Yes sure I will do this, I was just asking to know if I need to do this now or if it can wait. I would say it can wait

**Comment by andreab1997** [comment]
> > > yes, `yadism` can indeed provide all SV (both ren and fact) at all orders (you have to request it though)
> > 
> > 
> > wait at N3LO on ren scale are available in yadism: [NNPDF/yadism#150](https://github.com/NNPDF/yadism/issues/150)
> 
> you're right and I'm wrong - there is neither fact. nor ren. SV at N3LO in yadism :scream: the ren should be here, but it isn't: https://github.com/NNPDF/yadism/blob/3a2552c8e3c53f7d80c1d5d5b159c00df9240b8f/src/yadism/esf/scale_variations.py#L129
> 
> > > I was more worried about n3loxs or Higgs (or in general the N3LO pheno)
> > 
> > 
> > So far I was using the scale varied KF or computing sv directly using the given n3lo code, but I believe this feature can be quite useful in pineko in future. And it doesn't require much work.
> 
> does this mean we the N3LO fits are safe for the moment? (or do we need to panic?)

What? N3LO sv are not in yadism then?

**Comment by giacomomagni** [comment]
But what about this then ? We added only NNLO ?
 
https://github.com/NNPDF/yadism/pull/174/files

**Comment by felixhekhorn** [comment]
> But what about this then ? We added only NNLO? Aren't we messing up with names?
> 
> https://github.com/NNPDF/yadism/pull/174/files

you're right - I'm sorry, I successfully confused myself ... I was remembering correctly in the first place - for yadism $m=0$ (in the MHOU paper language) and so everything shifts one order up ... good, yadism is safe!

however, here in pineko we could not rely on $m=0$ of course

**Comment by giacomomagni** [comment]
> does this mean we the N3LO fits are safe for the moment? (or do we need to panic?)

So my understanding is that N3LO fits should be safe as the variant with DY KF should come with SV in the kfactor and `vp-setupfit` is able to deal with them. 

Regarding the baseline Ren scale variations at N3LO will come from yadism.
