### ISSUE TITLE
`mu0` scale is not updated correctly in the operator cards.

### ISSUE THREAD

**Issue by giacomomagni** [NNPDF/pineko#146]
We have a potential problem in the function that writes the operator cards, if the `Q0` scale provided in the theory card is not the same as the one defined as `mu0` in the template. 

In particular here: 

https://github.com/NNPDF/pineko/blob/f653ee289edcb98222b7e76572dac2d3465c2e08/src/pineko/evolve.py#L84

we should add something as:

```
operators_card["mu0"] = tcard["Q0"]
```

Thanks @toonhasenack  and @Radonirinaunimi

**Comment by felixhekhorn** [comment]
I agree, this is an oversight.

PS: remember that in https://github.com/NNPDF/eko/pull/295 we also shift $n_{f,0}$ from theory to operator

**Comment by giacomomagni** [comment]
> PS: remember that in https://github.com/NNPDF/eko/pull/295 we also shift nf,0 from theory to operator

okay thanks for the reminder. That one do not require an hot fix now, right?

**Comment by giacomomagni** [comment]
I feel we have been lucky here...

**Comment by felixhekhorn** [comment]
> okay thanks for the reminder. That one do not require an hot fix now, right?

no that is still for the now v0.15 series and unmerged

> I feel we have been lucky here...

I agree :see_no_evil:
