### ISSUE TITLE
evolution of fragmentation function grids

### ISSUE THREAD

**Issue by t7phy** [NNPDF/pineko#157]
We need two additions to pineko for the possibility of transforming fragmentation function grids to fktables:

1) we need to be able to perform time-like evolution, which is already possible with eko so I think it should be direct?

2) for scale variations, we need 3 scales instead of 2, i.e. besides mu_ren and mu_fact, we also need mu_frag. for this, i am unsure of how simple or complicated it would be, but very soon when we implement SIDIS code, this would be needed.

**Comment by felixhekhorn** [comment]
1. solved by #158 
2. will be solved when we get closer to actually needing it
