### ISSUE TITLE
How to deal with jets

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/pineko#16]
the hacks I needed for jets (i.e. https://github.com/NNPDF/fktables/blob/main/split_grid.py https://github.com/NNPDF/fktables/blob/main/jets_build.sh https://github.com/NNPDF/fktables/blob/86927f9460f8bbaf7f4daab0789c2d32283d3f2d/fkutils/builder.py#L76 https://github.com/NNPDF/fktables/blob/86927f9460f8bbaf7f4daab0789c2d32283d3f2d/fkutils/builder.py#L173 ) I did *not* port, but I hope https://github.com/N3PDF/eko/pull/105 will be available soon

_Originally posted by @felixhekhorn in https://github.com/N3PDF/pineko/issues/12#issuecomment-1069200534_

**Comment by felixhekhorn** [comment]
Mmm I'd rather prefer to not have this inside the "core `pineko`" as this is too much of a special case; still we could bind the "hacks" to the repo as a special command: `pineko jets SUBCOMMAND` ...

**Comment by AleCandido** [comment]
Maybe `pineko split` sounds a bit less custom than `pineko jets`, but once N3PDF/eko#105 (and the subsequent companion PR) will be available, the split will be there out of the box.

**Comment by AleCandido** [comment]
Ok, that's correct

**Comment by felixhekhorn** [comment]
solved with eko v0.13.1
