### ISSUE TITLE
Compatibility between NNPDF and pineko theory cards

### ISSUE THREAD

**Issue by LucianHL** [NNPDF/pineko#197]
Hi, me again I am afraid!

I am looking to run pineko with the new 40_000_000 and 40_001_000 (p. charm) theory IDs. If I take the .yaml card directly from e.g. [here](https://github.com/NNPDF/nnpdf/blob/master/nnpdf_data/nnpdf_data/theory_cards/40000000.yaml) and place it in the data/theory_cards/ folder then this crashes when producing the operator card. Comparing with the example [here](https://data.nnpdf.science/pineko/data_files/data/theory_cards/) there are some differences which when updated (i.e. copied across from 400.yaml) do fix things. The 40_000_000  card is in particular missing:

- ModSV, EScaleVar, IB, MaxNfAs, MaxNfPdf, Qedref, SxOrd, SxRes, global_nx, nfref and nf0

I don't think all of these are needed to not crash, but some are. Of course 'not crashing' and actually producing something sensible are different things, so any guidance here would be appreciated - can I just copy across the relevant flags from 400.yaml?

In addition, I have noticed that 'NfFF' takes a different value between the two cards, which seems strange.

**Comment by scarlehoff** [comment]
Hi @LucianHL , if you want to use the cards from NNPDF make sure you are using pineko with nnpdf true https://pineko.readthedocs.io/en/latest/overview/running.html#using-pineko-with-nnpdf

**Comment by LucianHL** [comment]
Hi @scarlehoff thank you. Doing that it still crashes with the default 40000000.yaml card though - it is still looking for 'ModSV' (and probably the other flags).

**Comment by scarlehoff** [comment]
If you are using this in `pineko.toml`
```
[general]
nnpdf=true
```

(and installed the code with `pip install .[nnpdf]`) it should be taking the card from the NNPDF repository (and not the one you copied)

If you instead want you use a custom card yes, you need to e.g., take one from the example and modify it.

(the idea is that when creating an nnpdf theory, the card used is the one committed to the repository, and it is read with the [reader](https://github.com/NNPDF/nnpdf/blob/master/nnpdf_data/nnpdf_data/theory.py#L27) from the repository, etc )

Otherwise you can get the runcard for the example and modify it to resemble the one from the nnpdf repo.

**Comment by LucianHL** [comment]
Thanks, if I try 

`pip install pineko[nnpdf]`

I am getting

WARNING: pineko 0.4.5 does not provide the extra 'nnpdf'?

**Comment by scarlehoff** [comment]
Oh, I didn't realize you were using the official releases. I'm afraid everything I said is for the latest version: `pip install "pineko[nnpdf] @  git+git://github.com/nnpdf/pineko.git"`

**Comment by LucianHL** [comment]
Thank you! Yes that works or to be precise:

`pip install 'pineko[nnpdf] @  git+https://github.com/nnpdf/pineko.git'`

**Comment by felixhekhorn** [comment]
good the issue got resolved! And don't worry about complaining, we want to get better and you can help us :upside_down_face: 

> In addition, I have noticed that 'NfFF' takes a different value between the two cards, which seems strange.

just wanted to add a clarification: that value should actually not matter in any case as by default we use FONLL which has not a fixed flavor number

**Comment by LucianHL** [comment]
Thanks both - ah ok that's good to know @felixhekhorn
