### ISSUE TITLE
Prepend `theory_` to theory card name 

### ISSUE THREAD

**Issue by giacomomagni** [NNPDF/pineko#60]
In order to have the possibility of storing all the theory cards in a single place I propose to prepend the string `theory_` to the theory ID and change this line accordingly:

https://github.com/NNPDF/pineko/blob/f7164fa8df0bf78a2cde71dd30fede24779d4e47/src/pineko/theory_card.py#L24

This should make the syntax compatible to the one used in pinefarm [here](https://github.com/NNPDF/runcards/blob/7f11afce4242791acad47d4c7be393e629b5121d/pinefarm/cli/list.py#L22) and validphys:

**Comment by AleCandido** [comment]
Fine by me :)

Instead of changing the pattern in that place, lift the pattern top level, such that is accessible from outside and we don't rely on many instances of the same string:

```py
def theory_file(id: int) -> str:
    return f"theory_{id}.yaml"
```

**Comment by giacomomagni** [comment]
This should be solved now.

**Comment by giacomomagni** [comment]
Yes, but I think `pinefarm` has changed now:

https://github.com/NNPDF/pinefarm/blob/main/src/pinefarm/cli/list.py#L22-L24

and here:

https://github.com/NNPDF/pinefarm/blob/main/src/pinefarm/cli/list.py#L44-L55

So it doesn't require `theory_` explicitly, 
and the issue has been solved the other way round.
