### ISSUE TITLE
Add option to remove (or modify behaviour) progress bar

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/pineko#65]
The progress bar looks nice but if one is in a metered or low-bandwith connection over ssh the constant update apparently takes quite some data.

**Comment by cschwan** [comment]
I think this will be fixed with the move to `Grid::evolve` in PineAPPL which doesn't show any progress, because it's much faster.

**Comment by scarlehoff** [comment]
"It's so much faster that it doesn't need a progress bar", that's a good tag line :P

**Comment by AleCandido** [comment]
In any case, I take the message, and we should add a `--no-interaction` global option.

**Comment by cschwan** [comment]
So technically this will be a non-issue when #49 will be merged.

**Comment by cschwan** [comment]
I did some performance tests in <https://github.com/NNPDF/pineappl/pull/184> where I implemented `Grid::evolve`, but as far as I remember the longest `Grid::evolve` ever spent was 2 minutes (Z pt, I think). Personally I dislike libraries (not programs) printing to stdout if everything goes OK, and I'd like to keep it that way and I rather spend more time on optimizing the code then showing a progress bar. If the code ever gets stuck, that's a bug and it should be fixed, of course. However, that shouldn't happen - maybe we'll just have to implement #49 and see how it 'feels'.

**Comment by scarlehoff** [comment]
We can have a "evolving, could take a few minutes..." and then most of the time takes seconds which makes people using it happy because it is so fast.

**Comment by AleCandido** [comment]
> We can have a "evolving, could take a few minutes..." and then most of the time takes seconds which makes people using it happy because it is so fast.

Indeed, this is a possible solution.
However, consider that Pineko itself is mostly used as a program, and PineAPPL CLI is also a program. So, being programs they have human users, and human users need UI (I agree on libraries, since they are consumed by other programs).

**Comment by felixhekhorn** [comment]
The problem is how to feed the information/progress from inside the library to the program outside ... (possible solutions might be a console argument or just a boolean argument ...)

**Comment by cschwan** [comment]
I suggest that we simply make the transition from `Grid::convolute_eko` to `Grid::evolve` and see if it's really a problem.

**Comment by felixhekhorn** [comment]
I still agree with @cschwan above - just to point out that this is (quasi) in conflict with https://github.com/NNPDF/pineline/issues/12

**Comment by scarlehoff** [comment]
The progress bar is gone as far as I can see.

**Comment by AleCandido** [comment]
> The progress bar is gone as far as I can see.

Yes, @cschwan speeded up PineAPPL evolution, such that we don't need it any longer, and we don't waste time deciding what to do :)
