### ISSUE TITLE
pineko cli is broken if used without config file

### ISSUE THREAD

**Issue by andreab1997** [NNPDF/pineko#74]
As discovered here #69, when some of the commands of the `pineko` cli are used without a valid configuration file, it fails even if only asked for the `--help`. One of the command is `pineko scaffold` of #69 but also `pineko theory` fails in the same way.

https://github.com/NNPDF/pineko/pull/69/files#r1060039961

**Comment by AleCandido** [comment]
A proposal for a solution might be to early return before loading the command, manually checking (with a helper function) if one of the tokens in `sys.argv` matches one of the `help_option_names`:
https://github.com/NNPDF/pineko/blob/67c4608a2dbc241b0c25a7ec2d70d0c713b084c2/src/pineko/cli/_base.py#L5

i.e.
```py
import sys

from ._base import CONTEXT_SETTINGS

def help_requested():
    return len(set(CONTEXT_SETTINGS["help_option_names"]) & set(sys.argv)) > 0
```
