### ISSUE TITLE
Fix click help - avoid running group code

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/pineko#78]
The problem *is* here: since this code is always run, also when the user is just asking for help.

I propose this should be solved in this PR, at least for this subcommand.

_Originally posted by @AleCandido in https://github.com/NNPDF/pineko/pull/69#discussion_r1060039961_

It's a complex task, and not deadly relevant. I now propose to postpone for later.

**Comment by felixhekhorn** [comment]
duplicate of #74
