### ISSUE TITLE
Scaffold from the theories repository

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/pineko#87]
One thing that might be useful is to add an option to `scaffold` to download some relevant data from the `theories` repo.

So one can do:

`pineko scaffold --theory 400`

and it will automatically download the theory runcard for 400 (and put it in the right place) and the operator template.

In favour/against ?

**Comment by AleCandido** [comment]
I agree it might be useful to have a good UI improvement to allow automated download of some assets, even if networking always involves a maintenance overhead (many more possible issues).

However, I'd not be against, but more for a separate command doing the job: `scaffold` will just ensure a consistent hierarchy, but right after you could `pineko download theory 400`.

**Comment by felixhekhorn** [comment]
- I agree on introducing a new subcommand - might or might not even come as an (PyPI) extra with additional dependency
- we're talking about downloading yamldb? +grids? i.e. not ekos and not fks

**Comment by scarlehoff** [comment]
> might or might not even come as an (PyPI) extra with additional dependency

It would not add extra dependencies. A simple download-from-github.raw

> we're talking about downloading yamldb? +grids? i.e. not ekos and not fks

Only `.yaml` files for the theories and the `_template` when available. We can think about downloading grids as well if need  be but we already decided at some point that they would not stay in github...

**Comment by felixhekhorn** [comment]
https://github.com/NNPDF/theories/issues/1
